import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const html = readFileSync(join(root, "src", "ui", "index.html"), "utf-8");
const tsContent = `// Auto-generated by scripts/inline-html.mjs — do not edit
export const INDEX_HTML: string = ${JSON.stringify(html)};
`;

const outDir = join(root, "src", "ui");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "_html.ts"), tsContent);
